package eulerProblems;

public class Number02 {
	/*
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
	 * By starting with 1 and 2, the first 10 terms will be:
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
	 * find the sum of the even-valued terms.
	 */

	public static void main(String[] args) {
		int counter = 0;
		int i = 1, j = 1, temp = i + j;
		while (temp < 4000000){
			if (temp % 2 == 0){
				counter += temp;
			}
			i = j;
			j = temp;
			temp = i + j;
		}
		System.out.println(counter);
	}

}
